spring.application.name=fakesmsc

logging.level.root=info

server.port=8088
server.tomcat.accept-count=800
server.tomcat.max-connections=10000
server.tomcat.threads.max=800
server.tomcat.threads.min-spare=200

spring.task.execution.pool.max-size=1000
spring.task.execution.pool.core-size=500
spring.task.execution.pool.queue-capacity=10000
